config/routes.rb
TicketTracking::Application.routes.draw do
  resources :comments

    devise_for :users

    root :to => 'tickets#new'

    resources :departments

    resources :tickets

    get 'tickets/:id/pwned' => 'tickets#take_ownership', :url_key => /[a-z]+-\d+/i, :as => :take_ownership

=begin
    get 'tickets' => 'tickets#index'
    get 'tickets/new' => 'tickets#new'
    get 'tickets/:url_key' => 'tickets#show', :url_key => /[a-z]+-\d+/i
    get 'tickets/:url_key/edit' => 'tickets#edit', :url_key => /[a-z]+-\d+/i
    post 'tickets/:url_key' => 'tickets#update', :url_key => /[a-z]+-\d+/i
    put 'tickets/:url_key' => 'tickets#create', :url_key => /[a-z]+-\d+/i
    delete 'tickets/:url_key' => 'tickets#delete', :url_key => /[a-z]+-\d+/i
=end

end

app/models/department.rb
class Department < ActiveRecord::Base
    has_many :users
    has_many :tickets

    validates :title, :presence => true
    validates :url_key, :presence => true, :format => /[A-Z]{3,}/i

    def url_key
        (read_attribute :url_key).upcase
    end

    def url_key=(value)
        write_attribute :url_key, value.upcase
    end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_filter :check_authentication, :only => [:index, :edit, :update, :destroy]
  before_action :set_department, :only => [:show, :edit, :update, :destroy]

  # GET /departments
  def index
    @departments = Department.all
  end

  # GET /departments/1
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  def create
    @department = Department.new(department_params)

    if @department.save
      redirect_to @department, notice: 'Department was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /departments/1
  def update
    if @department.update(department_params)
      redirect_to @department, notice: 'Department was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /departments/1
  def destroy
    @department.destroy
    redirect_to departments_url, notice: 'Department was successfully destroyed.'
  end

  private
    def check_authentication
      redirect_to '/' unless user_signed_in?
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def department_params
      params.require(:department).permit(:title, :url_key)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.haml
= form_for(@department) do |f|
  - if @department.errors.any?
    #error_explanation
      %h2
        #{ pluralize(@department.errors.count, "error") } prohibited this department from being saved:

      %ul
        - @department.errors.full_messages.each do |msg|
          %li
            = msg

  .field
    = f.label :title
    = f.text_field :title

  .field
    = f.label :url_key
    = f.text_field :url_key

  .actions
    = f.submit

app/views/departments/edit.html.erb
<h1>Editing department</h1>

<%= render 'form' %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

app/views/departments/index.html.erb
<h1>Listing departments</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url key</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.title %></td>
        <td><%= department.url_key %></td>
        <td><%= link_to 'Show', department %></td>
        <td><%= link_to 'Edit', edit_department_path(department) %></td>
        <td><%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Department', new_department_path %>

app/views/departments/new.html.haml
%h1
  Create department

= render 'form'

= link_to 'Back', departments_path

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @department.title %>
</p>

<p>
  <strong>Url key:</strong>
  <%= @department.url_key %>
</p>

<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>