config/routes.rb
TicketTracking::Application.routes.draw do
  resources :comments

    devise_for :users

    root :to => 'tickets#new'

    resources :departments

    resources :tickets

    get 'tickets/:id/pwned' => 'tickets#take_ownership', :url_key => /[a-z]+-\d+/i, :as => :take_ownership

=begin
    get 'tickets' => 'tickets#index'
    get 'tickets/new' => 'tickets#new'
    get 'tickets/:url_key' => 'tickets#show', :url_key => /[a-z]+-\d+/i
    get 'tickets/:url_key/edit' => 'tickets#edit', :url_key => /[a-z]+-\d+/i
    post 'tickets/:url_key' => 'tickets#update', :url_key => /[a-z]+-\d+/i
    put 'tickets/:url_key' => 'tickets#create', :url_key => /[a-z]+-\d+/i
    delete 'tickets/:url_key' => 'tickets#delete', :url_key => /[a-z]+-\d+/i
=end

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
    has_and_belongs_to_many :users
    belongs_to :department
    has_many :comments

    validates :title, :presence => true
    validates :body, :presence => true, :length => { :minimum => 4 }
    validates :url_key, :presence => true, :format => /[A-Z]{3,}-\d+/i, :uniqueness => true

    scope :unassigned, -> { where(:assignee_id => nil) }
    scope :open, -> { where(["status NOT IN (?)", [ :cancelled, :completed ]]) }
    scope :closed, -> { where(["status IN (?)", [:closed, :completed]]) }
    scope :on_hold, -> { where(:status => :on_hold) }
    scope :my, -> (email) { where(:assignee_id => User.find_by_email(email).id) }

    has_paper_trail

    # validates :status, :inclusion => { :in => statuses_available }

    def assignee
        assignee_id = read_attribute(:assignee_id)

        if assignee_id.present?
            User.find(assignee_id)
        else
            nil
        end
    end

    def assignee=(user)
        write_attribute(:assignee_id, user.id)
    end

    def status
        (read_attribute :status).to_sym
    end

    def status=(value)
        (write_attribute :status, value.to_s)
    end

    def self.statuses_available
        [ :waiting_for_staff, :waiting_for_customer, :on_hold, :cancelled, :completed ]
    end

    def self.status_options_available
        [ 
            [ 'Waiting for staff response', :waiting_for_staff ], 
            [ 'Waiting for customer response', :waiting_for_customer ], 
            [ 'On hold', :on_hold ],
            [ 'Cancelled', :cancelled ],
            [ 'Completed', :completed ] 
        ]
    end

    def status_string
        (self.class.status_options_available.select { |s| s[1] == status.to_sym })[0][0]
    end

    def to_param
        url_key
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
    before_action :set_ticket, only: [:show, :edit, :update, :destroy, :take_ownership]
    before_action :check_authentication, :only => [:index, :edit, :update, :destroy]

    # GET /tickets
    def index
        @tickets = case params[:filter]
            when 'closed' then Ticket.closed
            when 'on_hold' then Ticket.on_hold
            when 'open' then Ticket.open
            when 'unassigned' then Ticket.unassigned
            when 'my' then Ticket.my(current_user.email)
            else Ticket.all
        end
    end

    # GET /tickets/ABC-123
    def show
        if user_signed_in?
            @comment = Comment.new
        end
    end

    # GET /tickets/new
    def new
        @ticket = Ticket.new
    end

    # GET /tickets/ABC-123/edit
    def edit
    end

    def take_ownership
        @ticket.assignee = current_user
        @ticket.save

        redirect_to @ticket
    end

    # POST /tickets
    def create
        department = Department.find_by_url_key(params[:department])

        @ticket = department.tickets.new(ticket_params)

        @ticket.url_key = "#{ department.url_key }-#{ department.tickets.count + 1 }"
        @ticket.status = :waiting_for_staff

        NotificationMailer.ticket_submit_email(@ticket).deliver

        if @ticket.save
            redirect_to @ticket, notice: 'Ticket was successfully created.'
        else
            render action: 'new'
        end
    end

    # PATCH/PUT /tickets/ABC-123
    def update
        if @ticket.update(ticket_params)
            redirect_to @ticket, notice: 'Ticket was successfully updated.'
        else
            render action: 'edit'
        end
    end

    # DELETE /tickets/ABC-123
    def destroy
        @ticket.destroy
        redirect_to tickets_url, notice: 'Ticket was successfully destroyed.'
    end

    private
        def check_authentication
            redirect_to '/', :flash => { :error => "You should be logged in for seeing this!" } unless user_signed_in?
        end

        # Use callbacks to share common setup or constraints between actions.
        def set_ticket
            @ticket = Ticket.find_by_url_key(params[:id])
        end

        # Only allow a trusted parameter "white list" through.
        def ticket_params
            params.require(:ticket).permit(:title, :body, :department, :reporter_name, :reporter_email, :assignee_id, :status)
        end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.haml
.ui.form.bottom.attached.segment
    = form_for(@ticket) do |f| 
        - if @ticket.errors.any?
            .ui.error.message
                %i.close.icon
                .header
                    Whoops...

                %ul
                    - @ticket.errors.full_messages.each do |msg|
                        %li
                            = msg

        .field
            .ui.left.labeled.icon.input
                = f.text_field :reporter_name, :placeholder => 'Your name'

                %i.user.icon
                .ui.corner.label
                    %i.icon.asterisk

        .field
            .ui.left.labeled.icon.input
                = f.text_field :reporter_email, :placeholder => 'Your email'

                %i.mail.icon
                .ui.corner.label
                    %i.icon.asterisk

        .field
            = label_tag :department, 'Department'
            = select_tag :department, options_from_collection_for_select(Department.all, 'url_key', 'title')

        .field
            .ui.left.labeled.input
                = f.text_field :title, :placeholder => "Name your ticket"

                .ui.corner.label
                    %i.icon.asterisk

        .field
            .ui.left.labeled.input
                = f.text_area :body, :placeholder => "Describe what's happening"

                .ui.corner.label
                    %i.icon.asterisk

        .actions
            = f.submit :class => 'ui blue submit button'

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.haml
.ui.form.attached.message
    .header
        Tickets list

.ui.attached.segment
    .ui.secondary.menu
        - current_filter = params[:filter]

        = link_to 'All', tickets_path, :class => "item #{ 'active' if current_filter.blank? }"

        = link_to 'Assigned to myself', url_for(:controller => :tickets, :action => :index, :filter => 'my'), :class => "item #{ "active" if current_filter == "my" }"

        = link_to 'Unassigned', url_for(:controller => :tickets, :action => :index, :filter => 'unassigned'), :class => "item #{ "active" if current_filter == "unassigned" }"

        = link_to 'Open', url_for(:controller => :tickets, :action => :index, :filter => 'open'), :class => "item #{ "active" if current_filter == "open" }"

        = link_to 'On hold', url_for(:controller => :tickets, :action => :index, :filter => 'on_hold'), :class => "item #{ "active" if current_filter == "on_hold" }"

        = link_to 'Closed', url_for(:controller => :tickets, :action => :index, :filter => 'closed'), :class => "item #{ "active" if current_filter == "closed" }"

.ui.attached.bottom.segment
    %table.ui.sortable.table.segment
        %thead
            %tr
                %th
                    Title

                %th
                    Status

                %th
                    Assignee

        %tbody
            - @tickets.each do |ticket|
                %tr
                    %td
                        = link_to ticket.title, ticket

                    %td.warning
                        = ticket.status_string

                    %td
                        = ticket.assignee.present? ? ticket.assignee.email : 'nobody'

app/views/tickets/new.html.haml
.ui.attached.message
    .header
        Submit a new ticket

= render 'form'

app/views/tickets/show.html.haml
- if notice.present?
    .ui.info.message
        %i.close.icon
        .header
            Note

        = notice

- if @ticket.blank?
    .ui.error.message
        %i.close.icon
        .header
            Whoops...

        Seems that such ticket does not exist! Sorry!
-else
    .ui.attached.message
        .content
            .header
                = @ticket.title

        %p
            = @ticket.body

        %div
            .ui.red.label
                %i.code.icon
                = @ticket.status_string

            .ui.purple.label
                %i.bug.icon
                - if @ticket.assignee.present?
                    = @ticket.assignee.email
                - else
                    %strong{ :style => 'color: red' }
                        Nobody

            .ui.green.label
                %i.user.icon
                = @ticket.reporter_name

            .ui.green.label
                %i.time.icon
                = l @ticket.created_at


    - if user_signed_in?
        .ui.attached.form.fluid.segment
            .two.fields
                = form_for(@ticket) do |f|
                    .inline.field
                        %label
                            Status

                        = f.select :status, Ticket.status_options_available

                    .inline.field
                        %label
                            Assignee
                    
                        = f.select :assignee_id, User.all.map { |u| [ u.email, u.id ] }

                    = f.submit 'Update ticket', :class => 'ui blue submit button'

    .ui.attached.fluid.segment
        - @ticket.comments.each do |comment|
            .ui.secondary.segment
                %p
                    = comment.body

                %div
                    .ui.green.label
                        %i.user.icon
                        = comment.author.email

                    .ui.green.label
                        %i.time.icon
                        = l comment.created_at

    - if user_signed_in?                
        .ui.attached.form.fluid.segment
            .field
                = form_for(@comment) do |f|
                    = hidden_field_tag :ticket_url_key, @ticket.url_key

                    = f.text_area :body, :placeholder => 'Your comment'

                    = f.submit 'Reply', :class => 'ui blue submit button'